### ISSUE TITLE
Version for scala 2.12 is not published

### ISSUE THREAD

**Issue by justjoheinz** [iravid/play-json-cats#3]
Have a look at 
https://jcenter.bintray.com/com/iravid/

Maybe you just did `publish` instead of `+publish` ?

**Comment by iravid** [comment]
Sorry, missed your issue- it's published in my personal repo (https://dl.bintray.com/iravid/maven/com/iravid/play-json-cats_2.12/) but not copied to JCenter for some reason.

I'll open an issue with them. Thanks for pointing this out.

**Comment by iravid** [comment]
Fixed.
